services:
  - type: web
    name: django-tasktracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn tasktracker.wsgi:application
    envVars:
      - key: DEBUG
        value: false
